"""Output guardrail for schema validation, hallucination boundary checks, and citation verification."""

import re
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field


class Citation(BaseModel):
    """Structured citation reference."""
    doc_name: str
    page_number: int
    matched_chunk_id: Optional[str] = None
    is_valid: bool = True


class OutputGuardResult(BaseModel):
    """Result of output verification."""
    is_valid: bool
    sanitized_response: str
    verified_citations: List[Citation] = Field(default_factory=list)
    invalid_citations: List[str] = Field(default_factory=list)
    warnings: List[str] = Field(default_factory=list)


class OutputGuardrail:
    """Post-generation integrity and citation validation gatekeeper."""

    # Pattern matching [doc_name:page] or [doc_name:p.page]
    CITATION_PATTERN = re.compile(r"\[([^:\]\n]+):(?:p\.?|page\s*)?(\d+)\]", re.IGNORECASE)

    def extract_and_verify_citations(
        self,
        answer_text: str,
        retrieved_chunks: List[Dict[str, Any]]
    ) -> Tuple[List[Citation], List[str]]:
        """Extract inline citations from text and verify against retrieved context chunks."""
        matches = self.CITATION_PATTERN.findall(answer_text)
        verified: List[Citation] = []
        invalid: List[str] = []

        # Build lookup set of valid (doc_name, page_number)
        valid_sources: Dict[Tuple[str, int], str] = {}
        for chunk in retrieved_chunks:
            doc = chunk.get("doc_name", "").strip().lower()
            page = int(chunk.get("page_number", 1))
            cid = chunk.get("chunk_id", "")
            valid_sources[(doc, page)] = cid

        for doc_name, page_str in matches:
            clean_doc = doc_name.strip()
            clean_page = int(page_str)
            lookup_key = (clean_doc.lower(), clean_page)

            if lookup_key in valid_sources:
                verified.append(
                    Citation(
                        doc_name=clean_doc,
                        page_number=clean_page,
                        matched_chunk_id=valid_sources[lookup_key],
                        is_valid=True
                    )
                )
            else:
                invalid.append(f"[{clean_doc}:{clean_page}]")

        return verified, invalid

    def validate(
        self,
        answer_text: str,
        retrieved_chunks: List[Dict[str, Any]],
        faithfulness_score: float = 1.0,
        faithfulness_threshold: float = 0.70
    ) -> OutputGuardResult:
        """Validate generated answer, check citations, and enforce faithfulness threshold."""
        warnings: List[str] = []

        # Empty response check
        if not answer_text or not answer_text.strip():
            return OutputGuardResult(
                is_valid=False,
                sanitized_response="Error: Empty response generated by the model.",
                verified_citations=[],
                invalid_citations=[],
                warnings=["Empty response detected."]
            )

        # Citation validation
        verified_citations, invalid_citations = self.extract_and_verify_citations(
            answer_text, retrieved_chunks
        )

        if invalid_citations:
            warnings.append(f"Unverified citations detected: {', '.join(invalid_citations)}")

        if faithfulness_score < faithfulness_threshold:
            warnings.append(
                f"Faithfulness score ({faithfulness_score:.2f}) below threshold ({faithfulness_threshold:.2f})."
            )

        return OutputGuardResult(
            is_valid=True,
            sanitized_response=answer_text.strip(),
            verified_citations=verified_citations,
            invalid_citations=invalid_citations,
            warnings=warnings
        )
